#include "updateController.h"

#include <QDesktopServices>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonParseError>
#include <QNetworkReply>
#include <QRegularExpression>
#include <QTimer>
#include <QUrl>
#include <QVersionNumber>

#include "amneziaApplication.h"
#include "logger.h"
#include "core/utils/appUiConfig.h"
#include "core/utils/selfhosted/scriptsRegistry.h"
#include "version.h"

#if defined(Q_OS_ANDROID)
    #include "platforms/android/android_controller.h"
#endif

namespace
{
    Logger logger("UpdateController");

    constexpr int kUpdateRequestTimeoutMs = 15000;

#ifndef GIT_COMMIT_HASH
    #define GIT_COMMIT_HASH ""
#endif

    QString updateRepo()
    {
        return QString::fromLatin1(APP_GITHUB_UPDATE_REPO).trimmed();
    }

    [[maybe_unused]] QString releasesPageUrl()
    {
        return QStringLiteral("https://github.com/%1/releases").arg(updateRepo());
    }

    QUrl releasesListUrl()
    {
        return QUrl(QStringLiteral("https://api.github.com/repos/%1/releases?per_page=10").arg(updateRepo()));
    }

    QUrl releaseByTagUrl(const QString &tag)
    {
        return QUrl(QStringLiteral("https://api.github.com/repos/%1/releases/tags/%2")
                            .arg(updateRepo(), QString::fromLatin1(QUrl::toPercentEncoding(tag))));
    }

    // Asset names are generated by CI as "<name>_<version>_<platform>.<ext>", e.g.
    // "AmneziaVPN_5.0.1.1_linux_x64.run" or "AmneziaVPN_5.0.1.1.aab". The version is required to
    // have at least three components so that things like "android9+" cannot match.
    QString versionFromText(const QString &text)
    {
        static const QRegularExpression re(QStringLiteral("(?:^|[_\\-\\s(v])(\\d+(?:\\.\\d+){2,3})(?:[._\\-\\s)]|$)"));
        const QRegularExpressionMatch match = re.match(text);
        return match.hasMatch() ? match.captured(1) : QString();
    }

    // CI names the rolling release "... (v5.0.1.1 / 5c97d2f)"; pull the build commit out of it so
    // rebuilds of an unchanged version number can still be offered on a rolling channel.
    QString commitFromText(const QString &text)
    {
        static const QRegularExpression re(QStringLiteral("\\b([0-9a-f]{7,40})\\b\\s*\\)?\\s*$"));
        const QRegularExpressionMatch match = re.match(text.trimmed());
        return match.hasMatch() ? match.captured(1) : QString();
    }

    bool isSameCommit(const QString &a, const QString &b)
    {
        if (a.isEmpty() || b.isEmpty()) {
            return false;
        }
        return a.startsWith(b, Qt::CaseInsensitive) || b.startsWith(a, Qt::CaseInsensitive);
    }

    bool isReleaseEligible(const QJsonObject &release)
    {
        if (release.value(QStringLiteral("draft")).toBool()) {
            return false;
        }
        if (release.value(QStringLiteral("prerelease")).toBool() && !APP_GITHUB_UPDATE_ALLOW_PRERELEASE) {
            return false;
        }
        return true;
    }

    QString versionFromAssets(const QJsonArray &assets)
    {
        for (const QJsonValue &value : assets) {
            const QString version = versionFromText(value.toObject().value(QStringLiteral("name")).toString());
            if (!version.isEmpty()) {
                return version;
            }
        }
        return QString();
    }

    // Pick the installer this platform can actually run. The release is the authority on what it
    // published, so match against real asset names instead of composing a file name and hoping.
    QString platformAssetUrl(const QJsonArray &assets)
    {
#if defined(Q_OS_WINDOWS)
        const QLatin1String platformTag("windows");
        const QLatin1String extension(".exe");
#elif defined(Q_OS_MACOS) && !defined(MACOS_NE)
        const QLatin1String platformTag("macos");
        const QLatin1String extension(".pkg");
#elif defined(Q_OS_LINUX) && !defined(Q_OS_ANDROID)
        const QLatin1String platformTag("linux");
        const QLatin1String extension(".run");
#else
        Q_UNUSED(assets)
        return QString();
#endif

#if defined(Q_OS_WINDOWS) || (defined(Q_OS_MACOS) && !defined(MACOS_NE)) || (defined(Q_OS_LINUX) && !defined(Q_OS_ANDROID))
        for (const QJsonValue &value : assets) {
            const QJsonObject asset = value.toObject();
            const QString name = asset.value(QStringLiteral("name")).toString();
            if (name.contains(platformTag, Qt::CaseInsensitive) && name.endsWith(extension, Qt::CaseInsensitive)) {
                return asset.value(QStringLiteral("browser_download_url")).toString();
            }
        }
        return QString();
#endif
    }

    QStringList bulletsUnderHeading(const QString &body, const QString &headingPattern)
    {
        QStringList items;
        const QRegularExpression heading(QStringLiteral("^\\s*#{1,6}\\s*(?:%1)\\s*:?\\s*$").arg(headingPattern),
                                         QRegularExpression::CaseInsensitiveOption);
        const QRegularExpression anyHeading(QStringLiteral("^\\s*#{1,6}\\s+"));
        const QRegularExpression bullet(QStringLiteral("^\\s*[-*+]\\s+(.*\\S)\\s*$"));

        bool inSection = false;
        const QStringList lines = body.split(QRegularExpression(QStringLiteral("\\r?\\n")));
        for (const QString &line : lines) {
            if (heading.match(line).hasMatch()) {
                inSection = true;
                continue;
            }
            if (inSection && anyHeading.match(line).hasMatch()) {
                break;
            }
            if (!inSection) {
                continue;
            }
            const QRegularExpressionMatch item = bullet.match(line);
            if (item.hasMatch()) {
                items << item.captured(1);
            }
        }
        return items;
    }

    // Everything above the first markdown heading, used as the release summary.
    QString leadingText(const QString &body)
    {
        static const QRegularExpression anyHeading(QStringLiteral("^\\s*#{1,6}\\s+"));
        QStringList kept;
        const QStringList lines = body.split(QRegularExpression(QStringLiteral("\\r?\\n")));
        for (const QString &line : lines) {
            if (anyHeading.match(line).hasMatch()) {
                break;
            }
            kept << line;
        }
        return kept.join(QLatin1Char('\n')).trimmed();
    }

#if defined(Q_OS_WINDOWS)
    const QLatin1String kInstallerRemoteFileNamePattern("AmneziaVPN_%1_windows_x64.exe");
    const QString kInstallerLocalPath = QStandardPaths::writableLocation(QStandardPaths::TempLocation) + "/AmneziaVPN_installer.exe";
#elif defined(Q_OS_MACOS) && !defined(MACOS_NE)
    const QLatin1String kInstallerRemoteFileNamePattern("AmneziaVPN_%1_macos_x64.pkg");
    const QString kInstallerLocalPath = QStandardPaths::writableLocation(QStandardPaths::TempLocation) + "/AmneziaVPN.pkg";
#elif defined(Q_OS_LINUX) && !defined(Q_OS_ANDROID)
    const QLatin1String kInstallerRemoteFileNamePattern("AmneziaVPN_%1_linux_x64.run");
    const QString kInstallerLocalPath = QStandardPaths::writableLocation(QStandardPaths::TempLocation) + "/AmneziaVPN.run";
#endif

}

UpdateController::UpdateController(SecureAppSettingsRepository* appSettingsRepository, QObject *parent)
    : QObject(parent), m_appSettingsRepository(appSettingsRepository)
{
}

QString UpdateController::getVersion() const
{
    return m_version;
}

QString UpdateController::getReleaseDate() const
{
    return m_releaseDate;
}

QString UpdateController::getDescription() const
{
    return m_description;
}

QStringList UpdateController::getTags() const
{
    return m_tags;
}

QStringList UpdateController::getNewFeatures() const
{
    return m_newFeatures;
}

QStringList UpdateController::getImprovements() const
{
    return m_improvements;
}

QStringList UpdateController::getBugFixes() const
{
    return m_bugFixes;
}

UpdateState::State UpdateController::getUpdateState() const
{
    return m_updateState;
}

bool UpdateController::isStoreUpdate() const
{
#if defined(Q_OS_IOS) || defined(MACOS_NE)
    return true;
#elif defined(Q_OS_ANDROID)
    return AndroidController::instance()->isPlay();
#else
    return false;
#endif
}

void UpdateController::setUpdateState(UpdateState::State state)
{
    if (m_updateState == state) {
        return;
    }
    m_updateState = state;
    emit updateStateChanged();
}

bool UpdateController::isUpdateCheckRunning() const
{
    return m_updateCheckRunning;
}

void UpdateController::setUpdateCheckRunning(bool running)
{
    if (m_updateCheckRunning == running) {
        return;
    }
    m_updateCheckRunning = running;
    emit updateCheckRunningChanged();
}

void UpdateController::checkForUpdates()
{
    // Auto-update discovery via the Amnezia gateway has been removed: the v1/app_update request
    // carried the installation uuid, os/app version and distribution tag. This fork ships through
    // GitHub releases, so discovery is a plain unauthenticated GET against the releases API. It
    // sends no identifiers beyond what any HTTP client sends.
    if (m_updateCheckRunning) {
        return;
    }

    if (updateRepo().isEmpty()) {
        logger.info() << "In-app update discovery is disabled at build time";
        emit updateNotFound();
        return;
    }

    setUpdateCheckRunning(true);

    const QString tag = QString::fromLatin1(APP_GITHUB_UPDATE_TAG).trimmed();
    if (tag.isEmpty()) {
        requestReleases(releasesListUrl(), false);
    } else {
        requestReleases(releaseByTagUrl(tag), true);
    }
}

void UpdateController::requestReleases(const QUrl &url, bool byTag)
{
    QNetworkRequest request;
    request.setUrl(url);
    request.setTransferTimeout(kUpdateRequestTimeoutMs);
    request.setRawHeader("Accept", "application/vnd.github+json");
    request.setRawHeader("X-GitHub-Api-Version", "2022-11-28");
    request.setAttribute(QNetworkRequest::RedirectPolicyAttribute, QNetworkRequest::NoLessSafeRedirectPolicy);
    request.setHeader(QNetworkRequest::UserAgentHeader,
                      QStringLiteral("%1/%2").arg(QLatin1String(APPLICATION_NAME), QLatin1String(APP_VERSION)));

    QNetworkReply *reply = amnApp->networkManager()->get(request);

    QObject::connect(reply, &QNetworkReply::finished, this, [this, reply, byTag]() {
        reply->deleteLater();

        const int status = reply->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();

        if (reply->error() != QNetworkReply::NoError) {
            // A rolling tag can legitimately be absent (first build, renamed channel). Fall back to
            // the releases list once rather than reporting a failure the user cannot act on.
            if (byTag && status == 404) {
                logger.info() << "Release tag not found, falling back to the releases list";
                requestReleases(releasesListUrl(), false);
                return;
            }
            logger.error() << "Update check request failed:" << reply->errorString() << "HTTP status:" << status;
            setUpdateCheckRunning(false);
            emit updateCheckFailed();
            return;
        }

        QJsonParseError parseError {};
        const QJsonDocument doc = QJsonDocument::fromJson(reply->readAll(), &parseError);
        if (parseError.error != QJsonParseError::NoError) {
            logger.error() << "Update check response is not valid JSON:" << parseError.errorString();
            setUpdateCheckRunning(false);
            emit updateCheckFailed();
            return;
        }

        if (doc.isObject()) {
            const QJsonObject release = doc.object();
            finishCheck(isReleaseEligible(release) && applyRelease(release));
            return;
        }

        if (doc.isArray()) {
            // The list is newest first; only the newest eligible release is a candidate, so that an
            // older release can never be offered as an "update".
            for (const QJsonValue &value : doc.array()) {
                if (!value.isObject()) {
                    continue;
                }
                const QJsonObject release = value.toObject();
                if (!isReleaseEligible(release)) {
                    continue;
                }
                finishCheck(applyRelease(release));
                return;
            }
            logger.info() << "No eligible release found";
            finishCheck(false);
            return;
        }

        logger.error() << "Unexpected update check response shape";
        setUpdateCheckRunning(false);
        emit updateCheckFailed();
    });
}

bool UpdateController::applyRelease(const QJsonObject &release)
{
    const QJsonArray assets = release.value(QStringLiteral("assets")).toArray();
    const QString releaseName = release.value(QStringLiteral("name")).toString();
    const QString tagName = release.value(QStringLiteral("tag_name")).toString();

    // CI-generated asset names are the most reliable version source; the release title and tag are
    // fallbacks for hand-cut releases.
    QString version = versionFromAssets(assets);
    if (version.isEmpty()) {
        version = versionFromText(releaseName);
    }
    if (version.isEmpty()) {
        version = versionFromText(tagName);
    }

    const QVersionNumber remote = QVersionNumber::fromString(version);
    if (remote.isNull()) {
        logger.warning() << "Could not determine a version for release" << tagName;
        return false;
    }

    const QVersionNumber current = QVersionNumber::fromString(QString::fromLatin1(APP_VERSION));
    const QString remoteCommit = commitFromText(releaseName);
    const QString localCommit = QString::fromLatin1(GIT_COMMIT_HASH).trimmed();

    bool isNewer = false;
    if (remote > current) {
        isNewer = true;
    } else if (remote == current && !remoteCommit.isEmpty() && !isSameCommit(remoteCommit, localCommit)) {
        // Rolling channel: the version number does not move on every build, so a differing build
        // commit at the same version is still a newer build.
        isNewer = true;
    }

    if (!isNewer) {
        return false;
    }

    m_version = version;
    // published_at is an RFC 3339 timestamp; the UI only formats the date part.
    m_releaseDate = release.value(QStringLiteral("published_at")).toString().left(10);
    m_releasePageUrl = release.value(QStringLiteral("html_url")).toString();

    const QString body = release.value(QStringLiteral("body")).toString();
    m_description = leadingText(body);
    if (m_description.isEmpty()) {
        m_description = body.trimmed();
    }

    m_newFeatures = bulletsUnderHeading(body, QStringLiteral("new features?|features?"));
    m_improvements = bulletsUnderHeading(body, QStringLiteral("improvements?|changes?"));
    m_bugFixes = bulletsUnderHeading(body, QStringLiteral("bug ?fixes?|fixes?"));

    m_tags.clear();
    if (release.value(QStringLiteral("prerelease")).toBool()) {
        m_tags << tr("Pre-release");
    }
    if (!tagName.isEmpty()) {
        m_tags << tagName;
    }

    m_assetDownloadUrl = platformAssetUrl(assets);
    m_downloadBaseUrl = m_assetDownloadUrl.left(qMax(0, m_assetDownloadUrl.lastIndexOf(QLatin1Char('/'))));

    return true;
}

void UpdateController::finishCheck(bool found)
{
    setUpdateCheckRunning(false);

    if (!found) {
        logger.info() << "No application update available";
        emit updateNotFound();
        return;
    }

    logger.info() << "Application update available:" << m_version;
    setUpdateState(UpdateState::State::Idle);
    emit updateFound();
}

void UpdateController::openStorePage() const
{
#if defined(Q_OS_IOS)
    QDesktopServices::openUrl(QUrl(QLatin1String(APP_IOS_STORE_URL_FALLBACK)));
#elif defined(MACOS_NE)
    QDesktopServices::openUrl(QUrl(QStringLiteral("https://apps.apple.com/app/id1600529900")));
#elif defined(Q_OS_ANDROID)
    // Only the Play flavor should ever be sent to Play. A build installed from GitHub (F-Droid,
    // Obtainium, a sideloaded APK) has no Play listing to open, and on a device without Play
    // Services the intent would simply fail, so send it to the release it actually came from.
    if (AndroidController::instance()->isPlay()) {
        QDesktopServices::openUrl(
                QUrl(QStringLiteral("https://play.google.com/store/apps/details?id=%1").arg(QLatin1String(APP_ANDROID_PACKAGE))));
    } else {
        QDesktopServices::openUrl(QUrl(m_releasePageUrl.isEmpty() ? releasesPageUrl() : m_releasePageUrl));
    }
#endif
}

void UpdateController::startUpdate()
{
    if (isStoreUpdate()) {
        openStorePage();
        return;
    }

#if defined(Q_OS_ANDROID)
    // GitHub build on Android: open the release page in a browser, the system downloads the APK.
    const QString androidReleaseUrl = m_releasePageUrl.isEmpty() ? releasesPageUrl() : m_releasePageUrl;
    if (androidReleaseUrl.isEmpty()) {
        logger.error() << "Release page URL is empty";
        setUpdateState(UpdateState::State::DownloadError);
        return;
    }
    QDesktopServices::openUrl(QUrl(androidReleaseUrl));
#elif !defined(Q_OS_IOS) && !defined(MACOS_NE)
    downloadInstaller();
#endif
}

QString UpdateController::composeDownloadUrl() const
{
#if !defined(Q_OS_ANDROID) && !defined(Q_OS_IOS) && !defined(MACOS_NE)
    // Prefer the asset the release actually published over a composed file name.
    if (!m_assetDownloadUrl.isEmpty()) {
        return m_assetDownloadUrl;
    }
    if (m_downloadBaseUrl.isEmpty() || m_version.isEmpty()) {
        return QString();
    }
    const QString fileName = QString(kInstallerRemoteFileNamePattern).arg(m_version);
    return m_downloadBaseUrl + "/" + fileName;
#else
    return QString();
#endif
}

void UpdateController::downloadInstaller()
{
#if !defined(Q_OS_ANDROID) && !defined(Q_OS_IOS) && !defined(MACOS_NE)
    if (m_updateState == UpdateState::State::Downloading) {
        return;
    }

    const QString downloadUrl = composeDownloadUrl();
    if (downloadUrl.isEmpty()) {
        logger.error() << "Download URL is empty";
        setUpdateState(UpdateState::State::DownloadError);
        return;
    }

    setUpdateState(UpdateState::State::Downloading);

    QNetworkRequest request;
    request.setTransferTimeout(30000);
    request.setUrl(QUrl(downloadUrl));
    // Release assets are served via a redirect to objects.githubusercontent.com.
    request.setAttribute(QNetworkRequest::RedirectPolicyAttribute, QNetworkRequest::NoLessSafeRedirectPolicy);

    QNetworkReply *reply = amnApp->networkManager()->get(request);

    QObject::connect(reply, &QNetworkReply::finished, this, [this, reply]() {
        reply->deleteLater();

        if (reply->error() != QNetworkReply::NoError) {
            logger.error() << "Installer download failed, network error:" << static_cast<int>(reply->error())
                           << reply->errorString();
            logger.error() << "HTTP status:" << reply->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();
            setUpdateState(UpdateState::State::DownloadError);
            return;
        }

        QFile file(kInstallerLocalPath);
        if (!file.open(QIODevice::WriteOnly)) {
            logger.error() << "Failed to open installer file for writing:" << kInstallerLocalPath
                           << "Error:" << file.errorString();
            setUpdateState(UpdateState::State::DownloadError);
            return;
        }

        if (file.write(reply->readAll()) == -1) {
            logger.error() << "Failed to write installer data to file:" << kInstallerLocalPath
                           << "Error:" << file.errorString();
            file.close();
            setUpdateState(UpdateState::State::DownloadError);
            return;
        }

        file.close();
        setUpdateState(UpdateState::State::ReadyToInstall);
    });
#endif
}

void UpdateController::installUpdate()
{
#if !defined(Q_OS_ANDROID) && !defined(Q_OS_IOS) && !defined(MACOS_NE)
    if (m_updateState != UpdateState::State::ReadyToInstall) {
        logger.error() << "Installer is not downloaded yet";
        return;
    }

    #if defined(Q_OS_WINDOWS)
    runWindowsInstaller(kInstallerLocalPath);
    #elif defined(Q_OS_MACOS) && !defined(MACOS_NE)
    runMacInstaller(kInstallerLocalPath);
    #elif defined(Q_OS_LINUX) && !defined(Q_OS_ANDROID)
    runLinuxInstaller(kInstallerLocalPath);
    #endif
#endif
}

#if defined(Q_OS_WINDOWS)
int UpdateController::runWindowsInstaller(const QString &installerPath)
{
    qint64 pid;
    bool success = QProcess::startDetached(installerPath, QStringList(), QString(), &pid);

    if (success) {
        logger.info() << "Installation process started with PID:" << pid;
    } else {
        logger.error() << "Failed to start installation process";
        return -1;
    }

    return 0;
}
#endif

#if defined(Q_OS_MACOS) && !defined(MACOS_NE)
int UpdateController::runMacInstaller(const QString &installerPath)
{
    // Create temporary directory for extraction
    QTemporaryDir extractDir;
    extractDir.setAutoRemove(false);
    if (!extractDir.isValid()) {
        logger.error() << "Failed to create temporary directory";
        return -1;
    }
    logger.info() << "Temporary directory created:" << extractDir.path();

    // Create script file in the temporary directory
    QString scriptPath = extractDir.path() + "/mac_installer.sh";
    QFile scriptFile(scriptPath);
    if (!scriptFile.open(QIODevice::WriteOnly)) {
        logger.error() << "Failed to create script file";
        return -1;
    }

    // Get script content from registry
    QString scriptContent = amnezia::scriptData(amnezia::ClientScriptType::mac_installer);
    if (scriptContent.isEmpty()) {
        logger.error() << "macOS installer script content is empty";
        scriptFile.close();
        return -1;
    }

    scriptFile.write(scriptContent.toUtf8());
    scriptFile.close();
    logger.info() << "Script file created:" << scriptPath;

    // Make script executable
    QFile::setPermissions(scriptPath, QFile::permissions(scriptPath) | QFile::ExeUser);

    // Start detached process
    qint64 pid;
    bool success =
            QProcess::startDetached("/bin/bash", QStringList() << scriptPath << extractDir.path() << installerPath, extractDir.path(), &pid);

    if (success) {
        logger.info() << "Installation process started with PID:" << pid;
    } else {
        logger.error() << "Failed to start installation process";
        return -1;
    }

    return 0;
}
#endif

#if defined(Q_OS_LINUX) && !defined(Q_OS_ANDROID)
int UpdateController::runLinuxInstaller(const QString &installerPath)
{
    QFile::setPermissions(installerPath, QFile::permissions(installerPath) | QFile::ExeUser);

    qint64 pid;
    bool success = QProcess::startDetached(installerPath, QStringList(), QString(), &pid);

    if (success) {
        logger.info() << "Installation process started with PID:" << pid;
    } else {
        logger.error() << "Failed to start installation process";
        return -1;
    }

    return 0;
}
#endif
